#!/bin/bash
# https://mybinder.readthedocs.io/en/latest/config_files.html#postbuild-run-code-after-installing-the-environment
echo "running postBuild"
set -ex

# installing webquiz
# https://tex.stackexchange.com/questions/73016/how-do-i-install-an-individual-package-on-a-linux-system
TARGET=$(kpsewhich -var-value TEXMFLOCAL)
sudo mkdir -p "$TARGET"
cd "$TARGET"
sudo wget http://mirrors.ctan.org/macros/latex/contrib/webquiz.zip
sudo unzip webquiz.zip
sudo rm webquiz.zip
sudo mktexlsr
